# Generated by Django 3.2 on 2023-08-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osbposts', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='author',
        ),
    ]
