# Generated by Django 3.2 on 2023-08-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osb_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to='user_uploads'),
        ),
    ]
