"""empty message

Revision ID: 3c78137ff935
Revises: ca6a401f3854
Create Date: 2021-04-09 12:09:57.831605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c78137ff935'
down_revision = 'ca6a401f3854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dib_settings', sa.Column('url1', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url2', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url3', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url4', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url5', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dib_settings', 'url5')
    op.drop_column('dib_settings', 'url4')
    op.drop_column('dib_settings', 'url3')
    op.drop_column('dib_settings', 'url2')
    op.drop_column('dib_settings', 'url1')
    # ### end Alembic commands ###
