"""Added F1Teams sandboxing

Revision ID: 8b589a912a69
Revises: b738ea6d68ae
Create Date: 2021-03-27 18:42:30.027749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b589a912a69'
down_revision = 'b738ea6d68ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f1_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.String(length=64), nullable=True),
    sa.Column('team_afkorting', sa.String(length=3), nullable=True),
    sa.Column('rijder_1', sa.String(length=64), nullable=True),
    sa.Column('rijder_2', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_afkorting')
    )
    op.create_index(op.f('ix_f1_teams_teamname'), 'f1_teams', ['teamname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_f1_teams_teamname'), table_name='f1_teams')
    op.drop_table('f1_teams')
    # ### end Alembic commands ###
