"""empty message

Revision ID: ca6a401f3854
Revises: c5d14fd099da
Create Date: 2021-04-09 12:05:39.274527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6a401f3854'
down_revision = 'c5d14fd099da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dib_settings', sa.Column('url1', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url2', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url3', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url4', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url5', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dib_settings', 'url5')
    op.drop_column('dib_settings', 'url4')
    op.drop_column('dib_settings', 'url3')
    op.drop_column('dib_settings', 'url2')
    op.drop_column('dib_settings', 'url1')
    # ### end Alembic commands ###
