"""empty message

Revision ID: f27a50cc95cf
Revises: 238ce5e7c85a
Create Date: 2021-03-29 17:37:18.553525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27a50cc95cf'
down_revision = '238ce5e7c85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_timestamp'), 'articles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_timestamp'), table_name='articles')
    op.drop_column('articles', 'timestamp')
    # ### end Alembic commands ###
