"""empty message

Revision ID: d1aaaf28e0aa
Revises: dfd06d99c39f
Create Date: 2021-04-15 14:07:49.315641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aaaf28e0aa'
down_revision = 'dfd06d99c39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.add_column('dib_entries', sa.Column('image', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url1', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url2', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url3', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url4', sa.String(), nullable=True))
    op.add_column('dib_settings', sa.Column('url5', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dib_settings', 'url5')
    op.drop_column('dib_settings', 'url4')
    op.drop_column('dib_settings', 'url3')
    op.drop_column('dib_settings', 'url2')
    op.drop_column('dib_settings', 'url1')
    op.drop_column('dib_entries', 'image')
    op.drop_table('db_images')
    # ### end Alembic commands ###
